/**
 * @module core/openapi
 *
 * Machine-generated documentation for the Better Auth endpoints this package
 * mounts. Two halves:
 *
 *   1. `getAuthOpenApiDocument(auth)` — asks the *live* instance for its
 *      OpenAPI document, so paths, request bodies, responses and schemas can
 *      never drift from the plugins and providers actually enabled.
 *   2. `mergeAuthOpenApiDocument(target, document, options)` — a pure function
 *      that folds that document into a host application's OpenAPI 3.1
 *      document. It owns the two things an app cannot guess: prefixing the
 *      generated paths with the auth base path, and folding Better Auth's
 *      security schemes into the host's own scheme names.
 *
 * Nothing here is Hono-specific (the document endpoint is the app's), and
 * nothing here reads secrets: the generated document describes shapes and
 * routes, not values.
 */

import type { AuthInstance } from './auth'
import { normalizeAuthBasePath } from './routes'

// ── Document shape ─────────────────────────────────────────────────────────

/** A Better Auth path item: an OpenAPI `PathItemObject` keyed by HTTP method. */
export type AuthOpenApiPathItem = Record<string, Record<string, unknown>>

export interface AuthOpenApiSecurityScheme {
  type: string
  description?: string
  in?: string
  name?: string
  scheme?: string
  [key: string]: unknown
}

export interface AuthOpenApiDocument {
  openapi: string
  info: { title: string; description: string; version: string }
  components: {
    schemas: Record<string, unknown>
    securitySchemes: Record<string, AuthOpenApiSecurityScheme>
  }
  /** Root-level requirement. Deliberately NOT merged (see `mergeAuthOpenApiDocument`). */
  security: Array<Record<string, string[]>>
  servers: Array<{ url: string }>
  tags: Array<{ name: string; description: string }>
  paths: Record<string, AuthOpenApiPathItem>
}

/** The subset of a host OpenAPI document this merge needs to be non-destructive. */
export interface OpenApiDocumentLike {
  paths?: Record<string, Record<string, unknown>>
  tags?: Array<{ name: string; description?: string }>
  components?: {
    schemas?: Record<string, unknown>
    securitySchemes?: Record<string, AuthOpenApiSecurityScheme>
    [key: string]: unknown
  }
  [key: string]: unknown
}

export interface MergeAuthOpenApiOptions {
  /**
   * Path prefix the auth handler is mounted under. Defaults to the instance's
   * configured base path (`/auth`), which is what `mountAuthRoutes` uses.
   * Better Auth generates paths relative to it, so merging without this
   * prefix yields a document full of 404s.
   */
  basePath?: string
  /**
   * Tag applied to every merged operation. Use it to file the auth endpoints
   * under the host application's own "Auth" tag. When omitted, the document's
   * own tags (`Default`, one per plugin) are kept and added to the host.
   */
  tag?: string
  /**
   * Host names for Better Auth's two security schemes. Better Auth always
   * emits `bearerAuth` and `apiKeyCookie`; a host that already declares its
   * own bearer/cookie schemes gets the auth operations pointed at *those*
   * instead of accumulating a second, duplicate definition of the same
   * mechanism.
   */
  bearerSecurityScheme?: string
  cookieSecurityScheme?: string
}

/** Better Auth's scheme names, and the defaults for the mapping above. */
const BEARER_SCHEME = 'bearerAuth'
const COOKIE_SCHEME = 'apiKeyCookie'

// ── Fetching the generated document ────────────────────────────────────────

/** One generated document per instance — generation walks every endpoint. */
const documentCache = new WeakMap<AuthInstance, Promise<AuthOpenApiDocument>>()

/**
 * The OpenAPI document for a live auth instance, generated by Better Auth's
 * OpenAPI plugin and cached per instance.
 *
 * Requires the OpenAPI plugin, which this package always registers (see
 * `plugins/server.ts`).
 */
export function getAuthOpenApiDocument(auth: AuthInstance): Promise<AuthOpenApiDocument> {
  const cached = documentCache.get(auth)
  if (cached) return cached

  const generated = documentCache
    .set(
      auth,
      (async () => {
        const generate = (
          auth.api as { generateOpenAPISchema?: () => Promise<AuthOpenApiDocument> }
        ).generateOpenAPISchema
        if (typeof generate !== 'function') {
          throw new Error(
            'Auth instance cannot generate an OpenAPI document: the better-auth OpenAPI plugin is not registered.',
          )
        }
        return generate.call(auth.api)
      })(),
    )
    .get(auth)!

  // A failed generation must not be cached: the caller's next attempt (e.g. a
  // retry on the next /docs request) should try again.
  void generated.catch(() => documentCache.delete(auth))

  return generated
}

// ── The one endpoint this package mounts outside Better Auth ────────────────

/**
 * `POST {basePath}/session/refresh` — registered by `mountAuthRoutes`, not by
 * Better Auth, so the generator cannot know about it. Documented here, next
 * to the mount that serves it, using the generated `User` / `Session` models
 * so the response shape stays single-sourced.
 */
const SESSION_REFRESH_PATH = '/session/refresh'

const SESSION_REFRESH_PATH_ITEM: AuthOpenApiPathItem = {
  post: {
    summary: 'Refresh the current session',
    description:
      'Performs a cache-bypassing session lookup. Useful immediately after a permission or role change, where the session cookie cache would otherwise serve stale data.',
    security: [{ [BEARER_SCHEME]: [] }, { [COOKIE_SCHEME]: [] }],
    responses: {
      200: {
        description: 'Fresh session state.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                user: { $ref: '#/components/schemas/User' },
                session: { $ref: '#/components/schemas/Session' },
              },
            },
          },
        },
      },
      401: { description: 'No active session.' },
      403: { description: 'Origin is not trusted.' },
    },
  },
}

// ── Merging ────────────────────────────────────────────────────────────────

/**
 * Fold a Better Auth document into a host OpenAPI 3.1 document, in place on a
 * shallow copy. Returns a new document; the target is not modified.
 *
 * Deliberately merged: paths (base-path-prefixed), `components.schemas`,
 * `components.securitySchemes` and — only when no single `tag` was requested —
 * the tags themselves.
 *
 * Deliberately *not* merged: `info`, `servers` and the root `security`. The
 * host owns its identity and its servers, and Better Auth's root requirement
 * (`apiKeyCookie` AND `bearerAuth`) would silently mark every unannotated
 * public operation in the host document as authenticated.
 *
 * Host definitions always win on a name clash: the host's operations were
 * generated from its own routes, and a Better Auth schema of the same name
 * must not redefine them.
 */
export function mergeAuthOpenApiDocument<T extends OpenApiDocumentLike>(
  target: T,
  document: AuthOpenApiDocument,
  options: MergeAuthOpenApiOptions = {},
): T {
  const basePath = normalizeAuthBasePath(options.basePath ?? '/auth')
  const bearerName = options.bearerSecurityScheme ?? BEARER_SCHEME
  const cookieName = options.cookieSecurityScheme ?? COOKIE_SCHEME
  const tag = options.tag

  const schemeNames: Record<string, string> = {
    [BEARER_SCHEME]: bearerName,
    [COOKIE_SCHEME]: cookieName,
  }

  const paths: Record<string, Record<string, unknown>> = { ...target.paths }
  for (const [path, pathItem] of Object.entries(document.paths)) {
    paths[`${basePath}${path}`] = adaptPathItem(pathItem, schemeNames, tag) as Record<
      string,
      unknown
    >
  }
  paths[`${basePath}${SESSION_REFRESH_PATH}`] = adaptPathItem(
    SESSION_REFRESH_PATH_ITEM,
    schemeNames,
    tag,
  ) as Record<string, unknown>

  const components = { ...target.components }
  const schemas = { ...components.schemas }
  for (const [name, schema] of Object.entries(document.components.schemas)) {
    if (!(name in schemas)) schemas[name] = schema
  }
  const securitySchemes = { ...components.securitySchemes }
  for (const [name, scheme] of Object.entries(document.components.securitySchemes)) {
    const mapped = schemeNames[name] ?? name
    if (!(mapped in securitySchemes)) securitySchemes[mapped] = scheme
  }

  return {
    ...target,
    paths,
    components: { ...components, schemas, securitySchemes },
    ...(tag ? {} : { tags: mergeTags(target.tags, document.tags) }),
  }
}

/** Points a generated `security` requirement at the host's scheme names. */
function mapSecurityRequirement(security: unknown, schemeNames: Record<string, string>): unknown {
  if (!Array.isArray(security)) return security
  return security.map((requirement) =>
    requirement && typeof requirement === 'object'
      ? Object.fromEntries(
          Object.entries(requirement).map(([scheme, scopes]) => [
            schemeNames[scheme] ?? scheme,
            scopes,
          ]),
        )
      : requirement,
  )
}

function adaptPathItem(
  pathItem: AuthOpenApiPathItem,
  schemeNames: Record<string, string>,
  tag: string | undefined,
): AuthOpenApiPathItem {
  return Object.fromEntries(
    Object.entries(pathItem).map(([method, operation]) => {
      const adapted = { ...operation }
      if ('security' in adapted) {
        adapted.security = mapSecurityRequirement(adapted.security, schemeNames)
      }
      if (tag) adapted.tags = [tag]
      return [method, adapted]
    }),
  )
}

function mergeTags(
  existing: Array<{ name: string; description?: string }> | undefined,
  incoming: Array<{ name: string; description: string }>,
): Array<{ name: string; description?: string }> {
  const tags = [...(existing ?? [])]
  const names = new Set(tags.map((entry) => entry.name))
  for (const entry of incoming) {
    if (names.has(entry.name)) continue
    names.add(entry.name)
    tags.push(entry)
  }
  return tags
}
