export { SearchTrigger } from './components/navigation.search-trigger'
export { CreateCourseButton } from './components/navigation.create-course-button'
export { useBreadcrumbs } from './hooks/navigation.breadcrumbs'
export { useSearch } from './hooks/navigation.search'
export { NAV_ITEMS, getVisibleNavItems, type NavItem } from './navigation.config'
