/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppContentLibraryRouteRouteImport } from './routes/_app/content-library/route'
import { Route as AppCoursesRouteRouteImport } from './routes/_app/courses/route'
import { Route as AppDashboardRouteRouteImport } from './routes/_app/dashboard/route'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppStudentsRouteRouteImport } from './routes/_app/students/route'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthMfaRouteImport } from './routes/_auth/mfa'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AppContentLibraryIndexRouteImport } from './routes/_app/content-library/index'
import { Route as AppCoursesIndexRouteImport } from './routes/_app/courses/index'
import { Route as AppCoursesCourseIdRouteImport } from './routes/_app/courses/$courseId'
import { Route as AppCoursesNewRouteImport } from './routes/_app/courses/new'
import { Route as AppCoursesReviewsRouteImport } from './routes/_app/courses/reviews'
import { Route as AppCoursesTemplatesRouteImport } from './routes/_app/courses/templates'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppDashboardRevenueRouteImport } from './routes/_app/dashboard/revenue'
import { Route as AppStudentsIndexRouteImport } from './routes/_app/students/index'
import { Route as AppStudentsBadgesRouteImport } from './routes/_app/students/badges'
import { Route as AppStudentsCohortsRouteImport } from './routes/_app/students/cohorts'
import { Route as AppStudentsMessagingRouteImport } from './routes/_app/students/messaging'
import { Route as AppStudentsRequestsRouteImport } from './routes/_app/students/requests'
import { Route as AppStudentsRulesRouteImport } from './routes/_app/students/rules'
import { Route as AppContentLibraryAssetIdIndexRouteImport } from './routes/_app/content-library/$assetId.index'
import { Route as AppContentLibraryAssetIdTranscriptRouteImport } from './routes/_app/content-library/$assetId.transcript'
import { Route as AppStudentsStudentIdIndexRouteImport } from './routes/_app/students/$studentId.index'
import { Route as AppStudentsStudentIdProgressRouteImport } from './routes/_app/students/$studentId.progress'
import { Route as AppCoursesCourseIdLessonsLessonIdRouteImport } from './routes/_app/courses/$courseId/lessons/$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContentLibraryRouteRoute = AppContentLibraryRouteRouteImport.update({
  id: '/content-library',
  path: '/content-library',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoursesRouteRoute = AppCoursesRouteRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRouteRoute = AppDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudentsRouteRoute = AppStudentsRouteRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppContentLibraryIndexRoute = AppContentLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContentLibraryRouteRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppCoursesCourseIdRoute = AppCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppCoursesNewRoute = AppCoursesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppCoursesReviewsRoute = AppCoursesReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppCoursesTemplatesRoute = AppCoursesTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRouteRoute,
} as any)
const AppDashboardRevenueRoute = AppDashboardRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AppDashboardRouteRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStudentsRouteRoute,
} as any)
const AppStudentsBadgesRoute = AppStudentsBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AppStudentsRouteRoute,
} as any)
const AppStudentsCohortsRoute = AppStudentsCohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => AppStudentsRouteRoute,
} as any)
const AppStudentsMessagingRoute = AppStudentsMessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => AppStudentsRouteRoute,
} as any)
const AppStudentsRequestsRoute = AppStudentsRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppStudentsRouteRoute,
} as any)
const AppStudentsRulesRoute = AppStudentsRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppStudentsRouteRoute,
} as any)
const AppContentLibraryAssetIdIndexRoute =
  AppContentLibraryAssetIdIndexRouteImport.update({
    id: '/$assetId/',
    path: '/$assetId/',
    getParentRoute: () => AppContentLibraryRouteRoute,
  } as any)
const AppContentLibraryAssetIdTranscriptRoute =
  AppContentLibraryAssetIdTranscriptRouteImport.update({
    id: '/$assetId/transcript',
    path: '/$assetId/transcript',
    getParentRoute: () => AppContentLibraryRouteRoute,
  } as any)
const AppStudentsStudentIdIndexRoute =
  AppStudentsStudentIdIndexRouteImport.update({
    id: '/$studentId/',
    path: '/$studentId/',
    getParentRoute: () => AppStudentsRouteRoute,
  } as any)
const AppStudentsStudentIdProgressRoute =
  AppStudentsStudentIdProgressRouteImport.update({
    id: '/$studentId/progress',
    path: '/$studentId/progress',
    getParentRoute: () => AppStudentsRouteRoute,
  } as any)
const AppCoursesCourseIdLessonsLessonIdRoute =
  AppCoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AppCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/content-library': typeof AppContentLibraryRouteRouteWithChildren
  '/courses': typeof AppCoursesRouteRouteWithChildren
  '/dashboard': typeof AppDashboardRouteRouteWithChildren
  '/students': typeof AppStudentsRouteRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/search': typeof AppSearchRoute
  '/login': typeof AuthLoginRoute
  '/mfa': typeof AuthMfaRoute
  '/signup': typeof AuthSignupRoute
  '/courses/$courseId': typeof AppCoursesCourseIdRouteWithChildren
  '/courses/new': typeof AppCoursesNewRoute
  '/courses/reviews': typeof AppCoursesReviewsRoute
  '/courses/templates': typeof AppCoursesTemplatesRoute
  '/dashboard/revenue': typeof AppDashboardRevenueRoute
  '/students/badges': typeof AppStudentsBadgesRoute
  '/students/cohorts': typeof AppStudentsCohortsRoute
  '/students/messaging': typeof AppStudentsMessagingRoute
  '/students/requests': typeof AppStudentsRequestsRoute
  '/students/rules': typeof AppStudentsRulesRoute
  '/content-library/': typeof AppContentLibraryIndexRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/students/': typeof AppStudentsIndexRoute
  '/content-library/$assetId/transcript': typeof AppContentLibraryAssetIdTranscriptRoute
  '/students/$studentId/progress': typeof AppStudentsStudentIdProgressRoute
  '/content-library/$assetId/': typeof AppContentLibraryAssetIdIndexRoute
  '/students/$studentId/': typeof AppStudentsStudentIdIndexRoute
  '/courses/$courseId/lessons/$lessonId': typeof AppCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notifications': typeof AppNotificationsRoute
  '/search': typeof AppSearchRoute
  '/login': typeof AuthLoginRoute
  '/mfa': typeof AuthMfaRoute
  '/signup': typeof AuthSignupRoute
  '/courses/$courseId': typeof AppCoursesCourseIdRouteWithChildren
  '/courses/new': typeof AppCoursesNewRoute
  '/courses/reviews': typeof AppCoursesReviewsRoute
  '/courses/templates': typeof AppCoursesTemplatesRoute
  '/dashboard/revenue': typeof AppDashboardRevenueRoute
  '/students/badges': typeof AppStudentsBadgesRoute
  '/students/cohorts': typeof AppStudentsCohortsRoute
  '/students/messaging': typeof AppStudentsMessagingRoute
  '/students/requests': typeof AppStudentsRequestsRoute
  '/students/rules': typeof AppStudentsRulesRoute
  '/content-library': typeof AppContentLibraryIndexRoute
  '/courses': typeof AppCoursesIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/students': typeof AppStudentsIndexRoute
  '/content-library/$assetId/transcript': typeof AppContentLibraryAssetIdTranscriptRoute
  '/students/$studentId/progress': typeof AppStudentsStudentIdProgressRoute
  '/content-library/$assetId': typeof AppContentLibraryAssetIdIndexRoute
  '/students/$studentId': typeof AppStudentsStudentIdIndexRoute
  '/courses/$courseId/lessons/$lessonId': typeof AppCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/content-library': typeof AppContentLibraryRouteRouteWithChildren
  '/_app/courses': typeof AppCoursesRouteRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRouteRouteWithChildren
  '/_app/students': typeof AppStudentsRouteRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/search': typeof AppSearchRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/mfa': typeof AuthMfaRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/courses/$courseId': typeof AppCoursesCourseIdRouteWithChildren
  '/_app/courses/new': typeof AppCoursesNewRoute
  '/_app/courses/reviews': typeof AppCoursesReviewsRoute
  '/_app/courses/templates': typeof AppCoursesTemplatesRoute
  '/_app/dashboard/revenue': typeof AppDashboardRevenueRoute
  '/_app/students/badges': typeof AppStudentsBadgesRoute
  '/_app/students/cohorts': typeof AppStudentsCohortsRoute
  '/_app/students/messaging': typeof AppStudentsMessagingRoute
  '/_app/students/requests': typeof AppStudentsRequestsRoute
  '/_app/students/rules': typeof AppStudentsRulesRoute
  '/_app/content-library/': typeof AppContentLibraryIndexRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/students/': typeof AppStudentsIndexRoute
  '/_app/content-library/$assetId/transcript': typeof AppContentLibraryAssetIdTranscriptRoute
  '/_app/students/$studentId/progress': typeof AppStudentsStudentIdProgressRoute
  '/_app/content-library/$assetId/': typeof AppContentLibraryAssetIdIndexRoute
  '/_app/students/$studentId/': typeof AppStudentsStudentIdIndexRoute
  '/_app/courses/$courseId/lessons/$lessonId': typeof AppCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/content-library'
    | '/courses'
    | '/dashboard'
    | '/students'
    | '/notifications'
    | '/search'
    | '/login'
    | '/mfa'
    | '/signup'
    | '/courses/$courseId'
    | '/courses/new'
    | '/courses/reviews'
    | '/courses/templates'
    | '/dashboard/revenue'
    | '/students/badges'
    | '/students/cohorts'
    | '/students/messaging'
    | '/students/requests'
    | '/students/rules'
    | '/content-library/'
    | '/courses/'
    | '/dashboard/'
    | '/students/'
    | '/content-library/$assetId/transcript'
    | '/students/$studentId/progress'
    | '/content-library/$assetId/'
    | '/students/$studentId/'
    | '/courses/$courseId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notifications'
    | '/search'
    | '/login'
    | '/mfa'
    | '/signup'
    | '/courses/$courseId'
    | '/courses/new'
    | '/courses/reviews'
    | '/courses/templates'
    | '/dashboard/revenue'
    | '/students/badges'
    | '/students/cohorts'
    | '/students/messaging'
    | '/students/requests'
    | '/students/rules'
    | '/content-library'
    | '/courses'
    | '/dashboard'
    | '/students'
    | '/content-library/$assetId/transcript'
    | '/students/$studentId/progress'
    | '/content-library/$assetId'
    | '/students/$studentId'
    | '/courses/$courseId/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/content-library'
    | '/_app/courses'
    | '/_app/dashboard'
    | '/_app/students'
    | '/_app/notifications'
    | '/_app/search'
    | '/_auth/login'
    | '/_auth/mfa'
    | '/_auth/signup'
    | '/_app/courses/$courseId'
    | '/_app/courses/new'
    | '/_app/courses/reviews'
    | '/_app/courses/templates'
    | '/_app/dashboard/revenue'
    | '/_app/students/badges'
    | '/_app/students/cohorts'
    | '/_app/students/messaging'
    | '/_app/students/requests'
    | '/_app/students/rules'
    | '/_app/content-library/'
    | '/_app/courses/'
    | '/_app/dashboard/'
    | '/_app/students/'
    | '/_app/content-library/$assetId/transcript'
    | '/_app/students/$studentId/progress'
    | '/_app/content-library/$assetId/'
    | '/_app/students/$studentId/'
    | '/_app/courses/$courseId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/content-library': {
      id: '/_app/content-library'
      path: '/content-library'
      fullPath: '/content-library'
      preLoaderRoute: typeof AppContentLibraryRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/mfa': {
      id: '/_auth/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/content-library/': {
      id: '/_app/content-library/'
      path: '/'
      fullPath: '/content-library/'
      preLoaderRoute: typeof AppContentLibraryIndexRouteImport
      parentRoute: typeof AppContentLibraryRouteRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/courses/$courseId': {
      id: '/_app/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AppCoursesCourseIdRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/courses/new': {
      id: '/_app/courses/new'
      path: '/new'
      fullPath: '/courses/new'
      preLoaderRoute: typeof AppCoursesNewRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/courses/reviews': {
      id: '/_app/courses/reviews'
      path: '/reviews'
      fullPath: '/courses/reviews'
      preLoaderRoute: typeof AppCoursesReviewsRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/courses/templates': {
      id: '/_app/courses/templates'
      path: '/templates'
      fullPath: '/courses/templates'
      preLoaderRoute: typeof AppCoursesTemplatesRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
    '/_app/dashboard/revenue': {
      id: '/_app/dashboard/revenue'
      path: '/revenue'
      fullPath: '/dashboard/revenue'
      preLoaderRoute: typeof AppDashboardRevenueRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppStudentsRouteRoute
    }
    '/_app/students/badges': {
      id: '/_app/students/badges'
      path: '/badges'
      fullPath: '/students/badges'
      preLoaderRoute: typeof AppStudentsBadgesRouteImport
      parentRoute: typeof AppStudentsRouteRoute
    }
    '/_app/students/cohorts': {
      id: '/_app/students/cohorts'
      path: '/cohorts'
      fullPath: '/students/cohorts'
      preLoaderRoute: typeof AppStudentsCohortsRouteImport
      parentRoute: typeof AppStudentsRouteRoute
    }
    '/_app/students/messaging': {
      id: '/_app/students/messaging'
      path: '/messaging'
      fullPath: '/students/messaging'
      preLoaderRoute: typeof AppStudentsMessagingRouteImport
      parentRoute: typeof AppStudentsRouteRoute
    }
    '/_app/students/requests': {
      id: '/_app/students/requests'
      path: '/requests'
      fullPath: '/students/requests'
      preLoaderRoute: typeof AppStudentsRequestsRouteImport
      parentRoute: typeof AppStudentsRouteRoute
    }
    '/_app/students/rules': {
      id: '/_app/students/rules'
      path: '/rules'
      fullPath: '/students/rules'
      preLoaderRoute: typeof AppStudentsRulesRouteImport
      parentRoute: typeof AppStudentsRouteRoute
    }
    '/_app/content-library/$assetId/': {
      id: '/_app/content-library/$assetId/'
      path: '/$assetId'
      fullPath: '/content-library/$assetId/'
      preLoaderRoute: typeof AppContentLibraryAssetIdIndexRouteImport
      parentRoute: typeof AppContentLibraryRouteRoute
    }
    '/_app/content-library/$assetId/transcript': {
      id: '/_app/content-library/$assetId/transcript'
      path: '/$assetId/transcript'
      fullPath: '/content-library/$assetId/transcript'
      preLoaderRoute: typeof AppContentLibraryAssetIdTranscriptRouteImport
      parentRoute: typeof AppContentLibraryRouteRoute
    }
    '/_app/students/$studentId/': {
      id: '/_app/students/$studentId/'
      path: '/$studentId'
      fullPath: '/students/$studentId/'
      preLoaderRoute: typeof AppStudentsStudentIdIndexRouteImport
      parentRoute: typeof AppStudentsRouteRoute
    }
    '/_app/students/$studentId/progress': {
      id: '/_app/students/$studentId/progress'
      path: '/$studentId/progress'
      fullPath: '/students/$studentId/progress'
      preLoaderRoute: typeof AppStudentsStudentIdProgressRouteImport
      parentRoute: typeof AppStudentsRouteRoute
    }
    '/_app/courses/$courseId/lessons/$lessonId': {
      id: '/_app/courses/$courseId/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof AppCoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof AppCoursesCourseIdRoute
    }
  }
}

interface AppContentLibraryRouteRouteChildren {
  AppContentLibraryIndexRoute: typeof AppContentLibraryIndexRoute
  AppContentLibraryAssetIdTranscriptRoute: typeof AppContentLibraryAssetIdTranscriptRoute
  AppContentLibraryAssetIdIndexRoute: typeof AppContentLibraryAssetIdIndexRoute
}

const AppContentLibraryRouteRouteChildren: AppContentLibraryRouteRouteChildren =
  {
    AppContentLibraryIndexRoute: AppContentLibraryIndexRoute,
    AppContentLibraryAssetIdTranscriptRoute:
      AppContentLibraryAssetIdTranscriptRoute,
    AppContentLibraryAssetIdIndexRoute: AppContentLibraryAssetIdIndexRoute,
  }

const AppContentLibraryRouteRouteWithChildren =
  AppContentLibraryRouteRoute._addFileChildren(
    AppContentLibraryRouteRouteChildren,
  )

interface AppCoursesCourseIdRouteChildren {
  AppCoursesCourseIdLessonsLessonIdRoute: typeof AppCoursesCourseIdLessonsLessonIdRoute
}

const AppCoursesCourseIdRouteChildren: AppCoursesCourseIdRouteChildren = {
  AppCoursesCourseIdLessonsLessonIdRoute:
    AppCoursesCourseIdLessonsLessonIdRoute,
}

const AppCoursesCourseIdRouteWithChildren =
  AppCoursesCourseIdRoute._addFileChildren(AppCoursesCourseIdRouteChildren)

interface AppCoursesRouteRouteChildren {
  AppCoursesCourseIdRoute: typeof AppCoursesCourseIdRouteWithChildren
  AppCoursesNewRoute: typeof AppCoursesNewRoute
  AppCoursesReviewsRoute: typeof AppCoursesReviewsRoute
  AppCoursesTemplatesRoute: typeof AppCoursesTemplatesRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
}

const AppCoursesRouteRouteChildren: AppCoursesRouteRouteChildren = {
  AppCoursesCourseIdRoute: AppCoursesCourseIdRouteWithChildren,
  AppCoursesNewRoute: AppCoursesNewRoute,
  AppCoursesReviewsRoute: AppCoursesReviewsRoute,
  AppCoursesTemplatesRoute: AppCoursesTemplatesRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
}

const AppCoursesRouteRouteWithChildren = AppCoursesRouteRoute._addFileChildren(
  AppCoursesRouteRouteChildren,
)

interface AppDashboardRouteRouteChildren {
  AppDashboardRevenueRoute: typeof AppDashboardRevenueRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteRouteChildren: AppDashboardRouteRouteChildren = {
  AppDashboardRevenueRoute: AppDashboardRevenueRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteRouteWithChildren =
  AppDashboardRouteRoute._addFileChildren(AppDashboardRouteRouteChildren)

interface AppStudentsRouteRouteChildren {
  AppStudentsBadgesRoute: typeof AppStudentsBadgesRoute
  AppStudentsCohortsRoute: typeof AppStudentsCohortsRoute
  AppStudentsMessagingRoute: typeof AppStudentsMessagingRoute
  AppStudentsRequestsRoute: typeof AppStudentsRequestsRoute
  AppStudentsRulesRoute: typeof AppStudentsRulesRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
  AppStudentsStudentIdProgressRoute: typeof AppStudentsStudentIdProgressRoute
  AppStudentsStudentIdIndexRoute: typeof AppStudentsStudentIdIndexRoute
}

const AppStudentsRouteRouteChildren: AppStudentsRouteRouteChildren = {
  AppStudentsBadgesRoute: AppStudentsBadgesRoute,
  AppStudentsCohortsRoute: AppStudentsCohortsRoute,
  AppStudentsMessagingRoute: AppStudentsMessagingRoute,
  AppStudentsRequestsRoute: AppStudentsRequestsRoute,
  AppStudentsRulesRoute: AppStudentsRulesRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
  AppStudentsStudentIdProgressRoute: AppStudentsStudentIdProgressRoute,
  AppStudentsStudentIdIndexRoute: AppStudentsStudentIdIndexRoute,
}

const AppStudentsRouteRouteWithChildren =
  AppStudentsRouteRoute._addFileChildren(AppStudentsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppContentLibraryRouteRoute: typeof AppContentLibraryRouteRouteWithChildren
  AppCoursesRouteRoute: typeof AppCoursesRouteRouteWithChildren
  AppDashboardRouteRoute: typeof AppDashboardRouteRouteWithChildren
  AppStudentsRouteRoute: typeof AppStudentsRouteRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSearchRoute: typeof AppSearchRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppContentLibraryRouteRoute: AppContentLibraryRouteRouteWithChildren,
  AppCoursesRouteRoute: AppCoursesRouteRouteWithChildren,
  AppDashboardRouteRoute: AppDashboardRouteRouteWithChildren,
  AppStudentsRouteRoute: AppStudentsRouteRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSearchRoute: AppSearchRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMfaRoute: typeof AuthMfaRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthMfaRoute: AuthMfaRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
