-- Revision 2 — Course Workspace Redesign (spec 00 §2.6).
--
-- Generated by `drizzle-kit generate` (bookkeeping: drizzle/meta/0022_snapshot.json
-- and the idx-22 journal entry are the generated ones and are in sync with
-- packages/database/src/schema). The DDL below is hand-hardened for environments
-- that already hold data, because drizzle emits unguarded statements:
--
--   * every statement is idempotent, so a re-run or a half-applied history is safe
--   * `entity_type` is backfilled explicitly before NOT NULL, rather than relying
--     on the ADD COLUMN default fill
--   * `lesson_id` is relaxed only after the backfill, because a `course` row has
--     no lesson (reversing the two fails on a populated table)
--
-- Applied and verified on an empty database AND against a populated table.
--
-- `drizzle-kit generate` also wanted to emit `DROP INDEX "idx_affiliates_email"`.
-- That is PRE-EXISTING drift unrelated to Revision 2: the index exists in the
-- 0021 snapshot but is absent from packages/database/src/schema/marketing/affiliates.ts
-- on master. Dropping an index as a side effect of a course-lifecycle migration
-- would be a surprise on staging/prod, so it is deliberately NOT included here.
-- See the branch commit message for the follow-up.

-- 1. Course lifecycle gains 'in_review', ordered between draft and published.
--    Postgres preserves enum ordering, so BEFORE/AFTER is what makes the
--    lifecycle progression real rather than an append.
ALTER TYPE "public"."course_status" ADD VALUE IF NOT EXISTS 'in_review' BEFORE 'published';

-- 2. Dual-entity review queue discriminator.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'review_entity_type') THEN
    CREATE TYPE "public"."review_entity_type" AS ENUM('course', 'item');
  END IF;
END
$$;

-- 3. Archive + review lifecycle timestamps.
--    `archived_at` is DISTINCT from the existing `deleted_at`: archive is a
--    reversible hide (spec 04 S-2.17), delete is not.
ALTER TABLE "courses"  ADD COLUMN IF NOT EXISTS "archived_at"          timestamp with time zone;
ALTER TABLE "courses"  ADD COLUMN IF NOT EXISTS "review_requested_at" timestamp with time zone;
ALTER TABLE "courses"  ADD COLUMN IF NOT EXISTS "review_decided_at"   timestamp with time zone;
ALTER TABLE "modules"  ADD COLUMN IF NOT EXISTS "archived_at"          timestamp with time zone;
ALTER TABLE "lessons"  ADD COLUMN IF NOT EXISTS "archived_at"          timestamp with time zone;

-- 4. BACKFILL FIRST, relax NOT NULL second. Every pre-existing row is a lesson
--    request, so it classifies as 'item'. The explicit UPDATE also covers a
--    re-run after a partial apply, where the column may exist without a default.
ALTER TABLE "review_requests" ADD COLUMN IF NOT EXISTS "entity_type" "public"."review_entity_type";

UPDATE "review_requests" SET "entity_type" = 'item' WHERE "entity_type" IS NULL;

ALTER TABLE "review_requests" ALTER COLUMN "entity_type" SET DEFAULT 'item';
ALTER TABLE "review_requests" ALTER COLUMN "entity_type" SET NOT NULL;

-- 5. Only now may lesson_id become nullable: course-level requests have no lesson.
ALTER TABLE "review_requests" ALTER COLUMN "lesson_id" DROP NOT NULL;

-- 6. lesson_id is now NULL for every course-level row, and a plain btree stores
--    all NULLs in one shared bucket — useless for the rows that now dominate the
--    column. Replace it with a partial index over the populated rows only.
DROP INDEX IF EXISTS "idx_review_requests_lesson";
CREATE INDEX IF NOT EXISTS "idx_review_requests_lesson"
  ON "review_requests" USING btree ("lesson_id")
  WHERE "lesson_id" IS NOT NULL;

-- 7. Partial index backing the publish-readiness queue query.
CREATE INDEX IF NOT EXISTS "idx_review_requests_open_course"
  ON "review_requests" USING btree ("course_id", "submitted_at")
  WHERE "entity_type" = 'course' AND "state" = 'pending';

-- 8. Keep the two row shapes consistent: 'course' => no lesson, 'item' => lesson.
ALTER TABLE "review_requests" DROP CONSTRAINT IF EXISTS "review_requests_subject_check";
ALTER TABLE "review_requests"
  ADD CONSTRAINT "review_requests_subject_check" CHECK (
    ("entity_type" = 'course' AND "lesson_id" IS NULL)
    OR ("entity_type" = 'item' AND "lesson_id" IS NOT NULL)
  );
